---
- hosts: all
  become: true

  tasks:
    - name: stop previous version docker
      shell: docker stop vishwajeet1321/scientific-calculator-webapp-devops
    - name: remove stopped container
      shell: docker rm -f vishwajeet1321/scientific-calculator-webapp-devops
    - name: remove docker images
      shell: docker image rm -f vishwajeet1321/scientific-calculator-webapp-devops:latest

    - name: create docker image
      shell: docker run -d -p 8085:8085 --name sci-cal vishwajeet1321/scientific-calculator-webapp-devops:latest