---
- name: Pull docker image of app
  hosts: all
  tasks:
    - name: stop previous version docker
      shell: [ "$(docker ps -a | grep scientifiCal)" ] && docker stop scientifiCal
    - name: remove stopped container
      shell: [ "$(docker ps -a | grep scientifiCal)" ] && docker rm -f scientifiCal
    - name: remove docker images
      shell: [ "$(docker ps -a | grep vishwajeet1321/scientific-calculator-webapp-devops)" ] && docker image rm -f vishwajeet1321/scientific-calculator-webapp-devops:latest

    - name: Pull app devops image
      docker_image:
        name: vishwajeet1321/scientific-calculator-webapp-devops
        source: pull