---
- name: Pull docker image of app
  hosts: all
  tasks:
    - name: stop previous version docker
      shell: if [ $( docker ps -a -f name=scientifiCal | wc -l ) -eq 2 ]; then docker stop scientifiCal; fi
    - name: remove stopped container
      shell: if [ $( docker ps -a -f name=scientifiCal | wc -l ) -eq 2 ]; then docker rm -f scientifiCal; fi
    - name: remove docker images
      shell: if [[ "$(docker images -q vishwajeet1321/scientific-calculator-webapp-devops:latest 2> /dev/null)"  ]]; then docker rmi vishwajeet1321/scientific-calculator-webapp-devops:latest ; fi

    - name: Pull app devops image
      docker_image:
        name: vishwajeet1321/scientific-calculator-webapp-devops
        source: pull