---
- name: Pull docker image of app
  hosts: all
  tasks:
    - name: stop previous version docker
      shell: docker stop vishwajeet1321/scientific-calculator-webapp-devops
    - name: remove stopped container
      shell: docker rm -f vishwajeet1321/scientific-calculator-webapp-devops
    - name: remove docker images
      shell: docker image rm -f vishwajeet1321/scientific-calculator-webapp-devops:latest

    - name: Pull app devops image
      docker_image:
        name: vishwajeet1321/scientific-calculator-webapp-devops
        source: pull